version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=dbpostgres
      - DB_PORT=5432
      - DB_NAME=dbname
      - DB_LOGIN=admin
      - DB_PASS=drowssap
      - PROVIDER_PORT=5000
    networks:
      - user-network
    depends_on:
      - dbpostgres

  dbpostgres:
    image: postgres:13
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: drowssap
    networks:
      - user-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  user-network:
    driver: bridge

volumes:
  postgres_data:
